Repository metno/aerovaldb, pull requests merged in 2025-03, with the labels that each got.

#122 Cache QueryEntries
  setup.cfg
  src/aerovaldb/__init__.py
  src/aerovaldb/aerovaldb.py
  src/aerovaldb/jsondb/backwards_compatibility.py
  src/aerovaldb/jsondb/jsonfiledb.py
  src/aerovaldb/sqlitedb/sqlitedb.py
  tests/test_aerovaldb.py
  tests/test_utils.py
Labels: enhancement, performance

#125 Adds endpoints for fairmode
  .gitignore
  setup.cfg
  src/aerovaldb/aerovaldb.py
  src/aerovaldb/jsondb/jsonfiledb.py
  src/aerovaldb/routes.py
  src/aerovaldb/sqlitedb/sqlitedb.py
  tests/test-db/json/project/experiment/fairmode/region_network_obsvar_layer.json
  tests/test-db/sqlite/test.sqlite
  tests/test_aerovaldb.py
Labels: enhancement

#127 try fix reports issue
  setup.cfg
  src/aerovaldb/jsondb/jsonfiledb.py
Labels: bug
